### PR TITLE
Nodejs/week2

### PR DESCRIPTION
**Pull request by ccshah298**

### CODE REVIEW

**Review by Ekamba — CHANGES_REQUESTED** [review]
You did a good job @ccshah298. I just want you to change the check validation you made in review-router.js here: `response.send("use incorrect format ");` to something like: `There is no reviews with ID: ${request.params.id}, use an existing ID`. The problem here is not really the format, but the wrong number.
And also in reservation-router.js, you can just say: `response.send("use correct ID");`, because just `response.send("use correct");` it doen't have a good meaning.
I also have a bit of dout in which case your else statement will be use.

**Comment by ccshah298** [comment]
Hi Ekamba , Thanks for reviewing my homework and giving me a feedback ..i will do changes as per your comments.. and my else statement works when user enter wrong string as id,it will throw an error..

**Comment by Ekamba** [comment]
> Hi Ekamba , Thanks for reviewing my homework and giving me a feedback ..i will do changes as per your comments.. and my else statement works when user enter wrong string as id,it will throw an error..

According to your code, if a user enter an existing ID the line number 17 (`return response.send(reservationWithid[0]);`) will run. And if a user enter an ID that doesn't exist the line number 12 (`response.send("use correct");` will run, I think your else statement an extra piece of code as you just have two cases. Hope you understand what I mean 👦🏽

**Comment by ccshah298** [comment]
ohk i get it now..Thanks :)

**Pull request merged**
